### ISSUE TITLE
Please update HerokuCLI to fetch newer versions (7.39.x)

### ISSUE THREAD

**Issue by hugo4711** [autopkg/gerardkok-recipes#147]
Updates seem stuck at 7.35.0

**Comment by gerardkok** [comment]
I get the impression Heroku no longer distributes an installable package. Instead it suggests to use homebrew to keep it updated. Building a munki package out of a Homebrew formula is too much work, I'm afraid, so I think it's best to no longer use the munki recipe to install Heroku. I'll deprecate it.
