### ISSUE TITLE
GPGtools keyserver

### ISSUE THREAD

**Issue by octomike** [autopkg/gerardkok-recipes#158]
Hi,

gpgtools import failed for us due to a signature verification failure. I saw your post https://gpgtools.tenderapp.com/discussions/problems/106355-teamgpgtoolsorg-key-expired and after running

```
gpg --keyserver hkps://keys.openpgp.org --refresh-keys
```

everything worked fine. But I wonder if this is worth fixing in the verifier script, because other people might hit this issue as well.

And thanks for maintaining these recipes, much appreciated!

**Comment by gerardkok** [comment]
Thanks for the suggestion, I finally had some time to put it in. Please let me know if it doesn't work.
