### ISSUE TITLE
Splunk autopkg not match found URL

### ISSUE THREAD

**Issue by 13tatavo** [autopkg/gerardkok-recipes#191]
Hi,

We are running a local override for the splunk munki recipe and we started to receive this below error message last week:

No match found on URL: https://www.splunk.com/en_us/download/universal-forwarder.html
Failed.

We create  a new override and also ran the original recipe, but receive the same error.

**Comment by gerardkok** [comment]
Looks like the download url had changed; I've fixed the regex. Please let me know if it doesn't work.
