### ISSUE TITLE
Recipe failed MySQLCommunityServer.munki.recipe

### ISSUE THREAD

**Issue by erolc5215** [autopkg/gerardkok-recipes#219]
Running Autopkg 2.7 and received the following error: 

The following recipes failed:
    MySQLCommunityServer.munki.recipe
        Expected processor MunkiOptionalReceiptEditor can't be found.

**Comment by gerardkok** [comment]
I'm afraid I can't replicate it. MunkiOptionalReceiptEditor was moved to Autopkg 2.7 (from https://github.com/autopkg/keeleysam-recipes/blob/master/GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py), although it wasn't in the release notes. Can you try reinstalling Autopkg and see if that helps?
