### ISSUE TITLE
DotNetCoreSDK.munki.recipe doesn't work anymore

### ISSUE THREAD

**Issue by arekdist** [autopkg/gerardkok-recipes#244]
```
Processing DotNetCoreSDK.munki.recipe...
URLTextSearcher
No match found on URL: https://dotnet.microsoft.com/download
Failed.
Receipt written to /Volumes/***/local.munki.DotNetCoreSDK/receipts/DotNetCoreSDK.munki-receipt-20240110-121257.plist

The following recipes failed:
    DotNetCoreSDK.munki.recipe
        Error in local.munki.DotNetCoreSDK: Processor: URLTextSearcher: Error: No match found on URL: https://dotnet.microsoft.com/download
```
Probably because of changes in URLs, current paths are:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.101-macos-x64-installer
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.101-macos-arm64-installer

while in the download.recipe we have:
<string>href="(?P&lt;intermediate_url&gt;/download/dotnet/thank-you/sdk-3\.[0-9\.]+-macos-x64-installer)"</string>

**Comment by gerardkok** [comment]
It looks like the .NET Core SDK (version 3) can no longer be downloaded, but instead you can now only download the .NET SDK (version 8). For this package, there's already a 'DotNetSDK' recipe, and this recipe uses the links you mention. I'll deprecate the DotNetCoreSDK recipe.
