### ISSUE TITLE
node.download Recipe Fails to Download

### ISSUE THREAD

**Issue by foigus** [autopkg/gerardkok-recipes#3]
When running the node.munki recipe, I receive the following error:

 node.munki.recipe
        Error in local.munki.node: Processor: URLTextSearcher: Error: No match found on URL: https://nodejs.org/download

It appears the page that URLTextSearcher is scraping:

https://nodejs.org/download/

Has changed in deference to:

https://nodejs.org/en/ (with the appropriate user-agent to trigger an offer of an OS X installer)
https://nodejs.org/dist/latest/

**Comment by gerardkok** [comment]
I just merged valdore86's pull request that should fix this, please test if this fixes your issue.

**Comment by foigus** [comment]
Seems to work for me--thanks!
