### ISSUE TITLE
Node.js shasums File Moved

### ISSUE THREAD

**Issue by foigus** [autopkg/gerardkok-recipes#6]
The shasums URL here:
https://github.com/autopkg/gerardkok-recipes/blob/master/Node.js/node.verify.recipe#L26

Appears to have changed from:
https://nodejs.org/dist/v%version%/SHASUMS.txt

to:
https://nodejs.org/dist/v%version%/SHASUMS256.txt

**Comment by timsutton** [comment]
[This change](https://github.com/autopkg/gerardkok-recipes/pull/5) should address this.

**Comment by gerardkok** [comment]
I've just merged Tim's change, please check if that fixes the recipe for you. If it doesn't, I'll look at it coming weekend (I'm afraid I don't have time to attend to it earlier).

**Comment by foigus** [comment]
Seems to work for me.
