### ISSUE TITLE
GPGSuite failing signature verification

### ISSUE THREAD

**Issue by cwhits** [autopkg/gerardkok-recipes#79]
```
GPGSuite.munki
com.github.autopkg.gerardkok-recipes.SharedProcessors/GPGSignatureVerifier: Error: Verifying signature failed
```

**Comment by cwhits** [comment]
Ugh, ignore me. I ran it with `-vvv` to get some more info and now it's working. 🤷‍♂️

**Comment by cwhits** [comment]
ok so it had to do with me running autopkg as root (shh, _I know, I know_).

Running `/usr/local/bin/gpg --recv-keys 00D026C4` as root throws an error `No route to host`. And adding hkp://keys.gnupg.net also gives that same error. I ran `gpg-connect-agent --dirmngr 'keyserver --hosttable'`  picked one that _only_ had  an IPv4 address and tried that and it worked.

`/usr/local/bin/gpg --keyserver hkp://pgpkeys.co.uk --recv-keys 00D026C4`

:yolo:

**Comment by thaddeusfernandes** [comment]
> Ugh, ignore me. I ran it with `-vvv` to get some more info and now it's working. 🤷‍♂️

Hi i am getting the same error. how did u fix it?
