### ISSUE TITLE
GPGSignatureVerifier Fails

### ISSUE THREAD

**Issue by kitzy** [autopkg/gerardkok-recipes#8]
It seems that the GPGSignitureVerifier is failing.

$ autopkg run ~/GithubLocal/kitzy-recipes/GPG\ Suite/GPGSuite.pkg.recipe 
Processing /Users/kitzy/GithubLocal/kitzy-recipes/GPG Suite/GPGSuite.pkg.recipe...
Verifying signature failed
Failed.

The following recipes failed:
    /Users/kitzy/GithubLocal/kitzy-recipes/GPG Suite/GPGSuite.pkg.recipe
        Error in com.github.kitzy.pkg.GPGSuite: Processor: com.github.autopkg.gerardkok-recipes.SharedProcessors/GPGSignatureVerifier: Error: Verifying signature failed

**Comment by gerardkok** [comment]
I cannot reproduce the issue, but then again my system is likely different from yours. Can you send me the output of `autopkg run -vvv ...`, that would hopefully give me a hint where to start looking.

**Comment by kitzy** [comment]
I'm unable to replicate this now as well. Must have been a fluke at the time.
